name: Create Pull Request

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'The id of the Descope project to update the repository from'
        required: true
      management_key:
        description: 'The management key for the Descope project'
        required: true

env:
  FILES_PATH: DescopeFiles
  BRANCH_NAME: descope/update-files

jobs:
  update:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files   
        uses: actions/checkout@v4

      - name: Export Requested Project
        id: export
        uses: descope/descopecli/.github/actions/export@validate-import
        with:
          project_id: ${{ inputs.project_id }}
          management_key: ${{ inputs.management_key }}
          descope_base_url: 'https://gil.descope.team'
          files_path: ${{ env.FILES_PATH }}

      - name: Check For Changes
        if: steps.export.outputs.changes_file == ''
        uses: andymckay/cancel-action@0.4

      - name: Notify If Cancelled
        if: steps.export.outputs.changes_file == ''
        shell: bash
        run: |
          echo "## Workflow Skipped" >> $GITHUB_STEP_SUMMARY
          echo ":information_source: There are no changes to commit from the input project." >> $GITHUB_STEP_SUMMARY

      - name: Compose Details
        id: compose
        if: steps.export.outputs.changes_file != ''
        env:
          GH_TOKEN: ${{ github.token }}
          DEFAULT_NAME: '${{ github.actor }}'
          DEFAULT_MAIL: '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
        run: |
          export PATH_PREFIX="${{ env.FILES_PATH }}/"
          {
            echo 'pr_body<<EOF'
            echo '### Description'
            echo 'Exported from project with id `${{ inputs.project_id }}`.'
            echo ''
            echo '### Changes'
            cat ${{ steps.export.outputs.changes_file }} | xargs -I '{}' sh -c 'echo "- \`${1#$PATH_PREFIX}\`"' - {}
            echo EOF
          } >> "$GITHUB_OUTPUT"
          NAME="$(gh api /users/$GITHUB_ACTOR | jq -r '.name // ""')"
          MAIL="$(gh api /users/$GITHUB_ACTOR | jq -r '.email // ""')"
          AUTHOR="${NAME:-$DEFAULT_NAME} <${MAIL:-$DEFAULT_MAIL}>"
          echo pr_author="$AUTHOR" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: steps.export.outputs.changes_file != ''
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          assignees: ${{ github.actor }}
          author: ${{ steps.compose.outputs.pr_author }}
          committer: ${{ steps.compose.outputs.pr_author }}
          commit-message: 'Update project data'
          title: 'Update project data'
          body: ${{ steps.compose.outputs.pr_body }}
